[package]
edition = "2021"
name = "tilia"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
background-service = { git = "https://github.com/aschey/background-service-rs", rev = "135e57f8fc812337e83570f839796cd5d6c9018e" }
bytes = "1"
futures = "0.3"
futures-cancel = { git = "https://github.com/aschey/futures-cancel", rev = "40760850d131f0f172d135170aae01d99714f717" }
once_cell = "1"
tokio = { version = "1", features = [
    "sync",
    "rt-multi-thread",
    "macros",
    "time",
    "io-util",
] }
bollard = { version = "0.14", optional = true }
pin-project-lite = { version = "0.2", optional = true }
tokio-util = "0.7"
tower = { version = "0.4", features = ["reconnect"] }
tower-rpc = { git = "https://github.com/aschey/tower-rpc", rev = "1fba9ff36d4f5f26311fd527e609d01d9f8eca6c", features = [
    "client",
    "server",
] }

tracing = "0.1"
tracing-subscriber = "0.3"

[features]
tcp = ["tower-rpc/tcp"]
ipc = ["tower-rpc/ipc"]
docker = ["bollard", "pin-project-lite"]
