[package]
edition = "2021"
name = "tilia"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
background-service = { git = "https://github.com/aschey/background-service-rs", rev = "1c1b4e5c3e11e3136c981e9a040817eed19b5507" }
bytes = "1"
futures = "0.3"
futures-cancel = { git = "https://github.com/aschey/futures-cancel", rev = "d2c20b78ff5c9e85aa892b51971cc1c1b6b22351" }
once_cell = "1"
tokio = { version = "1", features = [
    "sync",
    "rt-multi-thread",
    "macros",
    "time",
    "io-util",
] }
bollard = { version = "0.15", optional = true }
pin-project-lite = { version = "0.2", optional = true }
tokio-util = "0.7"
tower = { version = "0.4", features = ["reconnect"] }
tower-rpc = { git = "https://github.com/aschey/tower-rpc", rev = "4704276c6b9c320fb414816e027fa5284df21f91", features = [
    "client",
    "server",
] }

tracing = "0.1"
tracing-subscriber = "0.3"

[features]
tcp = ["tower-rpc/tcp"]
ipc = ["tower-rpc/ipc"]
docker = ["bollard", "pin-project-lite"]
