[package]
edition = "2021"
name = "tracing-ipc"
version = "0.1.0"

[dependencies]
futures = "0.3"
once_cell = "1"
parity-tokio-ipc = "0.9"
tokio = {version = "1", features = ["sync", "rt-multi-thread", "macros", "time", "io-util"]}
tracing = "0.1"
tracing-subscriber = "0.3"
