[package]
edition = "2021"
name = "tilia-console"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.26.1", features = ["event-stream"] }
futures = { version = "0.3.28" }
tilia-widget = { path = "../tilia-widget" }
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
ratatui = "0.21.0"
tower-rpc = { git = "https://github.com/aschey/tower-rpc", rev = "72f2d60708dc57d91e8330f7efbec77744f763c3", features = [
    "client",
    "server",
    "ipc",
] }
