[package]
edition = "2021"
name = "tilia-console"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.26.1", features = ["event-stream"] }
futures = { version = "0.3.28" }
tilia-widget = { path = "../tilia-widget", features = ["ipc"] }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
ratatui = "0.22.0"
tower-rpc = { git = "https://github.com/aschey/tower-rpc", rev = "1fba9ff36d4f5f26311fd527e609d01d9f8eca6c", features = [
    "client",
    "server",
    "ipc",
] }
