[package]
edition = "2021"
name = "tilia-console"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.26.1", features = ["event-stream"] }
futures = { version = "0.3.28" }
tilia-widget = { path = "../tilia-widget", features = ["ipc"] }
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros"] }
ratatui = "0.22.0"
tower-rpc = { git = "https://github.com/aschey/tower-rpc", rev = "e9ff2d4f54de6f7350842d9a559d5a8443e89023", features = [
    "client",
    "server",
    "ipc",
] }
